<statement> ::= <variable_initialization>|<object_initialization>|<logical_operator>|

#All variable initializations:
<variable_initialization> ::= <int_definition> | <terminating_real_definition> | <non_terminating_real_definition> | <complex_defintion> | <character_definition> | <string_definition>

#int initializations:
<int_definition> ::= "leng" <valid_user_given_name> "=" <integer> 
<integer> ::= "^(-{0,1}[0-9]+)$"

#real initializations:
<terminating_real_definition> ::= "fathom" <valid_user_given_name> "=" <terminating_real>
<terminating_real> ::= "^(-{0,1}[0-9]+\.{0,1}[0-9]*)$"

<non_terminating_real_definition> ::= "nt_fathom" <valid_user_given_name> "=" <non_terminating_real> 
<non_terminating_real> ::= <terminating_real> "\/" <terminating_real> | <terminating_real> "\^" <terminating_real>  |"^pi$" | "^eu$" | "^gr$"

#complex initializations:
<complex_defintion> ::= "astral" <valid_user_given_name> "=" <complex>
<complex> ::= <terminating_real> "\s*(\+|-)\s*" <terminating_real> "i" | <terminating_real>

#character initializations:
<character_definition> ::= "sigil" <valid_user_given_name> "=" <character>
<character> ::= "^`.{1}`$"

#string initializations:
<string_definition> ::= "inscript" <valid_user_given_name> "=" <string>
<string> ::= "`.+`"

#Dev Gifted initializations:
<valid_user_given_name> ::= "\S+"

#test output function prototype
<std_output_fn> ::= "banner\(" <valid_output> "\)"
<valid_output> ::= <valid_user_given_name> | <string> | <character> | <terminating_real> | <non_terminating_real> | <complex> | <integer>


#objects:
# spell -method
# tome -object
# press -class
# operators:
# arithmetic operators
# relational operators
# logical operators
# as the same as c++
# Control Structures:
# portal(younggruff:<condition>)
# portal(oldgruff:<condition>)
# portal(eldestgruff:<condition>)
# portal(<variable>:<value>)
# portal(<variable>:END_OF_THE_WORLD)
# loops:
# sealedtill(riddle:<condition>)
# sealtill(wait:<cycles>)
# I/O:
# banner()
# stimuli()
# Other Methods:
# to be decided